/**
 * Markdown report generation — full crawl report + AI fix backlog.
 */
import fs from "fs/promises";
import path from "path";
import { CrawlResult, IssueSummary, OverallAuditReport } from "../types.js";
import { generateFixBacklogMarkdown } from "../ai/recommendations.js";

export function generateCrawlMarkdown(result: CrawlResult): string {
  const lines: string[] = [];

  lines.push("# SEOForge Site Audit Report");
  lines.push("*Screaming Frog–grade crawl · Ahrefs-grade issue engine · AEO scoring*");
  lines.push("");
  lines.push(`**Target**: ${result.targetUrl}  `);
  lines.push(`**Crawl Date**: ${result.startedAt}  `);
  lines.push(`**Strategy**: ${result.strategy} · **Status**: ${result.status}  `);
  lines.push(`**Pages Crawled**: ${result.totalUrlsCrawled} (max depth ${result.maxDepthReached})  `);
  lines.push(`**Sitemap**: ${result.sitemapAccessible ? `Accessible (${result.sitemapUrlCount} URLs)` : "Unreachable"}  `);
  lines.push(`**Robots.txt**: ${result.robotsAccessible ? "Accessible" : "Unreachable"}  `);
  lines.push(
    `**Total Issues**: ${result.totalErrors} Errors, ${result.totalWarnings} Warnings, ${result.totalNotices} Notices  `
  );
  lines.push(`**Average AEO Score**: **${result.averageAeoScore}/100**  `);
  lines.push("");

  const sorted = [...result.issuesSummary].sort((a, b) => {
    const w = { Error: 3, Warning: 2, Notice: 1 };
    return w[b.severity] - w[a.severity] || b.affectedPages - a.affectedPages;
  });

  lines.push("## Issues Overview");
  lines.push("");
  lines.push("| Issue | Severity | Category | Affected | Change | Recommendation |");
  lines.push("| :--- | :--- | :--- | :--- | :--- | :--- |");

  if (sorted.length === 0) {
    lines.push("| None detected | ✅ Clean | — | 0 | 0 | All crawled pages satisfy SEO & AEO standards. |");
  } else {
    for (const issue of sorted) {
      const sev =
        issue.severity === "Error" ? "🔴 **Error**" : issue.severity === "Warning" ? "🟡 **Warning**" : "🔵 **Notice**";
      const change = issue.change > 0 ? `+${issue.change}` : `${issue.change}`;
      lines.push(
        `| **${issue.name}** | ${sev} | ${issue.category} | ${issue.affectedPages} | \`${change}\` | ${issue.recommendation} |`
      );
    }
  }
  lines.push("");

  lines.push("## AI Fix Recommendations (prioritized)");
  lines.push("");
  if (result.recommendations.length === 0) {
    lines.push("_No recommendations — the site is clean._");
  } else {
    for (const rec of result.recommendations.slice(0, 15)) {
      lines.push(
        `### ${rec.priority} · ${rec.name} — _${rec.affectedPages} page(s), effort ${rec.effort}_`
      );
      lines.push("");
      lines.push(rec.recommendation);
      lines.push("");
    }
    lines.push("_The complete fix backlog with before/after examples is in `reports/ai-fix-backlog-<date>.md`._");
    lines.push("");
  }

  lines.push("## Pages");
  lines.push("");
  lines.push("| URL | Status | TTFB | Words | H1 | In/Out | AEO | Schema | Issues |");
  lines.push("| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |");

  const pageSort = [...result.pages].sort((a, b) => a.depth - b.depth || a.url.localeCompare(b.url));
  for (const p of pageSort.slice(0, 200)) {
    const issues = p.auditIssues.length
      ? p.auditIssues.map((i) => `[${i.severity}] ${i.name}`).join("; ")
      : "None";
    lines.push(
      `| \`${p.url}\` | ${p.status} | ${p.ttfbMs ?? p.responseTimeMs}ms | ${p.wordCount} | ${p.h1Count} | ${p.incomingInternalLinks.length}/${p.outgoingInternalLinks.length} | ${p.aeo.score}/100 | ${p.schema.typesFound.join(", ") || "None"} | ${issues} |`
    );
  }
  if (pageSort.length > 200) {
    lines.push("");
    lines.push(`_…and ${pageSort.length - 200} more pages (see the dashboard or CSV export)._`);
  }
  lines.push("");

  lines.push("---");
  lines.push("*Generated by [SEOForge 2.0](https://github.com/Aryanban/seoforge) — local crawler, audit engine & MCP server.*");

  return lines.join("\n");
}

export async function saveMarkdownReport(
  result: CrawlResult | OverallAuditReport,
  baseDir: string = process.cwd()
): Promise<string> {
  const reportsDir = path.join(baseDir, "reports");
  await fs.mkdir(reportsDir, { recursive: true });
  const dateStr = new Date().toISOString().split("T")[0];

  const crawlPath = path.join(reportsDir, `crawl-${dateStr}.md`);
  await fs.writeFile(crawlPath, generateMarkdownReport(result), "utf-8");

  // The multi-domain OverallAuditReport has no AI recommendations; only the
  // single-site CrawlResult carries a prioritised fix backlog.
  const recs = (result as CrawlResult).recommendations;
  if (recs && recs.length > 0) {
    const backlogPath = path.join(reportsDir, `ai-fix-backlog-${dateStr}.md`);
    await fs.writeFile(backlogPath, generateFixBacklogMarkdown(recs), "utf-8");
  }

  return crawlPath;
}

/* ------------------------------------------------------------------ */
/* Legacy compat — v1 OverallAuditReport shape                         */
/* ------------------------------------------------------------------ */

export function generateMarkdownReport(report: any): string {
  if (report && report.pages !== undefined) {
    return generateCrawlMarkdown(report as CrawlResult);
  }
  return generateLegacyMarkdown(report);
}

function generateLegacyMarkdown(report: any): string {
  const lines: string[] = [];
  lines.push("# SEOForge Site Audit & AEO Report");
  lines.push("");
  lines.push(`**Project**: ${report.project}  `);
  lines.push(`**Crawl Date**: ${report.timestamp}  `);
  lines.push(`**Audited Domains**: ${report.domainsAudited}  `);
  lines.push(`**Total Issues**: ${report.totalErrors}E / ${report.totalWarnings}W / ${report.totalNotices}N  `);
  lines.push("");
  for (const res of report.results ?? []) {
    lines.push(`### ${res.domain.name} (${res.domain.url}) — ${res.passed ? "✅" : "⚠️"}`);
    lines.push(`- AEO: ${res.averageAeoScore}/100`);
    lines.push("");
  }
  return lines.join("\n");
}

export { generateFixBacklogMarkdown };
export type { IssueSummary };
